Repository Say-Better/Service-Server, pull requests merged in 2024-07, with the labels that each got.

#118 :sparkles: Feat: 교육자-학습자 연결 및 연결 코드 검사 API에 응답값 추가
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/ui/MemberController.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/ui/MemberControllerTest.kt
Labels: :sparkles: feature

#120 :sparkles: Feat: 학습자 초기정보 입력 API에 생년원일과 성별을 추가
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/LearnerService.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/ui/MemberController.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/ui/dto/MemberRequest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/ui/MemberControllerTest.kt
  storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Learner.kt
Labels: :sparkles: feature

#121 [Feature/115] 임시 로그인 api 구현
  build.gradle.kts
  clients/client-api/src/main/resources/client-api.yml
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/AuthFacade.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/helper/CommonLoginIdHelper.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/helper/EmailEncoderHelper.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/EducatorService.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/LearnerService.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/MemberService.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/exception/AuthException.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/ui/AuthController.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/ui/dto/AuthRequest.kt
  core/core-api/src/main/kotlin/io/say/better/global/config/properties/AesProperties.kt
  core/core-api/src/main/kotlin/io/say/better/global/config/security/SecurityAuthConfig.kt
  core/core-api/src/main/kotlin/io/say/better/global/utils/AesEncryptUtil.kt
  core/core-api/src/main/resources/auth.yml
  core/core-api/src/test/kotlin/io/say/better/ContextTest.kt
  core/core-api/src/test/kotlin/io/say/better/DevelopTest.kt
  core/core-api/src/test/kotlin/io/say/better/application/CoreApiApplicationTest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/EducatorFixtures.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/JwtTokenFixtures.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/LeanerFixtures.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/MemberFixtures.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/application/AuthFacadeTest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/application/helper/CommonLoginIdHelperTest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/application/helper/EmailEncoderHelperTest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/ui/AuthControllerTest.kt
  core/core-api/src/test/kotlin/io/say/better/support/test/BaseTest.kt
  core/core-api/src/test/kotlin/io/say/better/support/test/spec/Specs.kt
  core/core-common/src/main/kotlin/io/say/better/core/common/code/status/ErrorStatus.kt
  core/core-common/src/main/kotlin/io/say/better/core/common/constant/Provider.kt
  core/core-infra/src/main/resources/infra.yml
Labels: :test_tube: test, :sparkles: feature

#122 [Feature/116] 챗봇 API 연결
  clients/client-api/src/main/kotlin/io/say/better/client/chatbot/api/ChatbotApi.kt
  clients/client-api/src/main/kotlin/io/say/better/client/chatbot/client/ChatbotClient.kt
  clients/client-api/src/main/kotlin/io/say/better/client/chatbot/config/ChatbotFeignConfiguration.kt
  clients/client-api/src/main/kotlin/io/say/better/client/chatbot/dto/ChatbotRequest.kt
  clients/client-api/src/main/kotlin/io/say/better/client/chatbot/dto/ChatbotResponse.kt
  clients/client-api/src/main/resources/client-api.yml
  core/core-api/src/main/kotlin/io/say/better/domain/chatting/application/ChattingFacade.kt
  core/core-api/src/main/kotlin/io/say/better/domain/chatting/application/converter/ChattingResponseConverter.kt
  core/core-api/src/main/kotlin/io/say/better/domain/chatting/exception/ChattingException.kt
  core/core-api/src/main/kotlin/io/say/better/domain/chatting/ui/ChattingController.kt
  core/core-api/src/main/kotlin/io/say/better/domain/chatting/ui/dto/ChattingRequest.kt
  core/core-api/src/main/kotlin/io/say/better/domain/chatting/ui/dto/ChattingResponse.kt
  core/core-api/src/test/kotlin/io/say/better/domain/chatting/ui/ChattingControllerTest.kt
Labels: :wrench: chore, :test_tube: test, :sparkles: feature

#126 [Feature/125] API 문서 수정
  build.gradle.kts
  core/core-api/build.gradle.kts
  core/core-api/src/docs/asciidoc/chatbot.adoc
  core/core-api/src/docs/asciidoc/educator.adoc
  core/core-api/src/docs/asciidoc/index.adoc
  core/core-api/src/docs/asciidoc/leaner.adoc
  core/core-api/src/docs/asciidoc/solution.adoc
  core/core-api/src/docs/asciidoc/symbol.adoc
  core/core-api/src/main/kotlin/io/say/better/SayBetterApplication.kt
  core/core-api/src/main/kotlin/io/say/better/domain/chatting/ui/ChattingController.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/ui/AuthController.kt
  core/core-api/src/main/kotlin/io/say/better/domain/member/ui/MemberController.kt
  core/core-api/src/main/kotlin/io/say/better/domain/review/ui/ReviewController.kt
  core/core-api/src/main/kotlin/io/say/better/domain/solution/ui/SolutionController.kt
  core/core-api/src/main/kotlin/io/say/better/domain/test/ui/TestController.kt
  core/core-api/src/main/kotlin/io/say/better/global/config/docs/SwaggerConfig.kt
  core/core-api/src/main/kotlin/io/say/better/global/config/security/SecurityConfig.kt
  core/core-api/src/main/resources/application.yml
  core/core-api/src/main/resources/static/docs/index.html
  core/core-api/src/main/resources/swagger.yml
  core/core-api/src/test/kotlin/io/say/better/domain/chatting/ui/ChattingControllerTest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/ui/AuthControllerTest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/member/ui/MemberControllerTest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/review/ui/ReviewControllerTest.kt
  core/core-api/src/test/kotlin/io/say/better/domain/solution/ui/SolutionControllerTest.kt
  core/core-api/src/test/kotlin/io/say/better/support/test/docs/RestControllerTest.kt
  core/core-api/src/test/kotlin/io/say/better/support/util/RestDocsUtils.kt
  settings.gradle.kts
  storage/storage-mysql-kt/src/main/resources/mysql.yml
  tests/api-docs/build.gradle.kts
  tests/api-docs/src/main/kotlin/io/say/better/test/api/RestDocsUtils.kt
Labels: :recycle: refactor, :sparkles: feature

#128 [Feature/127] redis 설정 수정
  storage/storage-redis-kt/src/main/kotlin/io/say/better/storage/redis/RedisConfig.kt
  storage/storage-redis-kt/src/main/resources/redis.yml
Labels: :recycle: refactor, :sparkles: feature

#137 [Feature/136] enum converter 구현
  storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/common/converter/EnumAttributeConverter.kt
  storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/common/utils/CodedEnumUtil.kt
  storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/account/entity/Learner.kt
  storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/account/type/Gender.kt
Labels: :recycle: refactor, :sparkles: feature

#140 :sparkles: Feat: 솔루션 종료 시 음성 파일 업로드 API
  core/core-api/src/docs/asciidoc/solution.adoc
  core/core-api/src/main/kotlin/io/say/better/domain/review/application/impl/RecordService.kt
  core/core-api/src/main/kotlin/io/say/better/domain/review/application/impl/ReviewService.kt
  core/core-api/src/main/kotlin/io/say/better/domain/solution/application/SolutionFacade.kt
  core/core-api/src/main/kotlin/io/say/better/domain/solution/application/converter/RecordConverter.kt
  core/core-api/src/main/kotlin/io/say/better/domain/solution/ui/SolutionController.kt
  core/core-api/src/main/resources/static/docs/index.html
  core/core-api/src/test/kotlin/io/say/better/domain/solution/ui/SolutionControllerTest.kt
  core/core-common/src/main/kotlin/io/say/better/core/common/code/status/ErrorStatus.kt
  core/core-infra/src/main/kotlin/io/say/better/core/infra/enums/AwsS3Folder.kt
  storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/review/entity/Record.kt
  storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/review/repository/RecordReadRepository.kt
  storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/review/repository/ReviewReadRepository.kt
Labels: :sparkles: feature
